### ISSUE TITLE
Method notification URL

### ISSUE THREAD

**Issue by liamgold** [globalpayments/globalpayments-3ds-js#6]
I'm testing setting up 3D secure V2 locally, but when the method notification URL is called, the js is doing a GET request instead of a POST. Is there something I'm doing wrong in the current set up that would cause this?

**Comment by liamgold** [comment]
Thanks @footfish and @slogsdon - all the above seems to be working fine now.

I'm now experiencing a new issue within the .NET SDK not being able to connect to the payment gateway, logged over there https://github.com/globalpayments/dotnet-sdk/issues/16

**Comment by slogsdon** [comment]
@liamgold Glad to see you got this sorted as well. I do see a slight bug within your handler's client-side script. Instead of:

```csharp
var methodUrlResponse = JsonConvert.DeserializeObject<MethodUrlResponse>(methodUrlResponseString);

context.Response.Write($"<script src=\"/payment/globalpayments-3ds.min.js\"></script><script>GlobalPayments.ThreeDSecure.handleMethodNotification('{methodUrlResponse.ThreeDSServerTransID}');</script>");
```

you can use:

```csharp
// remove: var methodUrlResponse = JsonConvert.DeserializeObject<MethodUrlResponse>(methodUrlResponseString);

context.Response.Write($"<script src=\"/payment/globalpayments-3ds.min.js\"></script><script>GlobalPayments.ThreeDSecure.handleMethodNotification({methodUrlResponseString});</script>");
```

`handleMethodNotification` and `handleChallengeNotification` expect the first parameter to be an object literal.
