### ISSUE TITLE
Iframe timeout issue on method notification

### ISSUE THREAD

**Issue by footfish** [globalpayments/globalpayments-3ds-js#7]
checkVersion times out with iframe error. 

![2019-09-12examples_3ds_](https://user-images.githubusercontent.com/12461463/64794171-0a76ef00-d574-11e9-8510-bf2bc0300092.png)

![2019-09-12 15_44_23examples_3ds_](https://user-images.githubusercontent.com/12461463/64794370-490ca980-d574-11e9-8356-0f5b784190c8.png)

Network
![2019-09-12 15_48_42sdk_examples_3ds_](https://user-images.githubusercontent.com/12461463/64794763-e667dd80-d574-11e9-8bdf-55946186a3d3.png)

(minor change in stock js for better error message
![2019-09-12 15_46_27sdk_examples_3ds_](https://user-images.githubusercontent.com/12461463/64794557-8c671800-d574-11e9-831b-640386d6e1c7.png)
) 

Playground on an AWS ec2 here - https://34.255.10.36//vendor/globalpayments/php-sdk/examples/3ds/

**Comment by slogsdon** [comment]
@footfish Glad to see you got this sorted.

As a note, the library exports [`handleMethodNotification`](https://github.com/globalpayments/globalpayments-3ds-js/blob/master/src/index.ts#L199) that acts as a convenience method for sending the message to the parent window. You could rewrite your script in `acs-profile-completion.php` as:

```html
<script src="globalpayments-3ds.js"></script>
<script>
  GlobalPayments.ThreeDSecure.handleMethodNotification(
      // base64 decoded `threeDSMethodData`
      { threeDSServerTransID: 'a54fad53-8d9a-4cb4-8e48-831ff00b057c'}},
      // parent window's origin. optional if same origin
      'https://34.255.10.36'
  );
</script>
```

There's also a matching [`handleChallengeNotification`](https://github.com/globalpayments/globalpayments-3ds-js/blob/master/src/index.ts#L186) function for the challenge notification URL.
